repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: prometheus
    namespace: default
    chart: prometheus-community/kube-prometheus-stack
    values:
      - ./dgraph-prometheus-operator.yaml
      - grafana:
          adminPassword: {{ requiredEnv "GRAFANA_ADMIN_PASSWORD" }}
      {{/* Dgraph Kubernetes CronJob Monitoring Support */}}
      {{/* export DGRAPH_BACKUPS_ENABLED=1 to enabled this feature */}}
      {{- if env "DGRAPH_BACKUPS_ENABLED" }}
      - ./dgraph-backup-alert-rules.yaml
      {{- end }}
      {{- if env "DGRAPH_PAGERDUTY_ENABLED" }}
      - ./alertmanager-pagerduty.yaml.gotmpl
      {{- end }}
    disableValidation: true
